/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cargar_imagenes;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Keloc
 */
public class ImagenesFrame extends javax.swing.JFrame {

    /**
     * Creates new form ImagenesFrame
     */
    public ImagenesFrame() {
        initComponents();
        Image img = new ImageIcon("src\\main\\resources\\output.jpg").getImage();
        ImageIcon icon;
        icon = new ImageIcon(img.getScaledInstance(imgDisplay.getWidth(), imgDisplay.getHeight(), Image.SCALE_SMOOTH));
        imgDisplay.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgSelect = new javax.swing.JButton();
        imgDisplay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setForeground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgSelect.setBackground(new java.awt.Color(102, 204, 255));
        imgSelect.setForeground(new java.awt.Color(51, 51, 51));
        imgSelect.setText("Seleccionar Imagen");
        imgSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgSelectActionPerformed(evt);
            }
        });
        jPanel1.add(imgSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 360, 30));

        imgDisplay.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(imgDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 420, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgSelectActionPerformed
        String route = "", type = "";
        JFileChooser jf = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG", "PNG");
        jf.setFileFilter(filter);
        int res = jf.showOpenDialog(this);
        if (res == JFileChooser.APPROVE_OPTION){
            route = jf.getSelectedFile().getPath();
            Image img = new ImageIcon(route).getImage();
            ImageIcon icon;
            icon = new ImageIcon(img.getScaledInstance(imgDisplay.getWidth(), imgDisplay.getHeight(), Image.SCALE_SMOOTH));
            BufferedImage imageFile = null;
            imageFile = readFromFile(route, imgDisplay.getWidth(), imgDisplay.getHeight(), imageFile); 
            writeToFile(imageFile);
            imgDisplay.setIcon(icon);
        }
    }//GEN-LAST:event_imgSelectActionPerformed

    public static BufferedImage readFromFile(String route, int width, int height, BufferedImage image){
        try {
            File sample = new File(route);
            image = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
            image = ImageIO.read(sample);
        } catch (IOException e){
            System.out.println("ERROR: "+e.getMessage());
        }
        return image;
    }
    
    public static void writeToFile(BufferedImage img){
        try {
            File output = new File("src\\main\\resources\\output.jpg");
            ImageIO.write(img, "jpg", output);
            System.out.println("Si pudo");
        } catch (IOException e){
            System.out.println("ERROR: "+e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImagenesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImagenesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImagenesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImagenesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImagenesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgDisplay;
    private javax.swing.JButton imgSelect;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
